# Generated by Django 5.2.6 on 2025-09-13 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car_DB',
            fields=[
                ('car_brand', models.CharField(max_length=10)),
                ('order_id', models.IntegerField(primary_key=True, serialize=False)),
                ('car_model', models.CharField()),
                ('price', models.IntegerField()),
                ('purchase_date', models.DateField()),
            ],
        ),
    ]
